# Generated by Django 3.1.3 on 2020-12-07 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta_video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('gb', models.IntegerField()),
                ('bus', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppGestion.marca')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppGestion.tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Procesador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('frecuencia', models.IntegerField()),
                ('socket', models.CharField(max_length=50)),
                ('nucleos', models.IntegerField()),
                ('hilos', models.IntegerField()),
                ('arquitectura', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppGestion.marca')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppGestion.tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Placa_madre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('chipset', models.CharField(max_length=50)),
                ('memorias', models.CharField(max_length=50)),
                ('formato', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppGestion.marca')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppGestion.tipo')),
            ],
        ),
    ]
