# Generated by Django 3.1.3 on 2020-12-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placa_madre',
            name='imagen',
            field=models.ImageField(null=True, upload_to='placas_madre'),
        ),
        migrations.AddField(
            model_name='procesador',
            name='imagen',
            field=models.ImageField(null=True, upload_to='procesadores'),
        ),
        migrations.AddField(
            model_name='tarjeta_video',
            name='imagen',
            field=models.ImageField(null=True, upload_to='tarjetas_video'),
        ),
    ]
