# Generated by Django 3.1.3 on 2020-12-07 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestion', '0002_auto_20201207_1642'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tarjeta_video',
        ),
    ]
