# Generated by Django 3.1.3 on 2020-12-07 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestion', '0003_delete_tarjeta_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta_video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('gpu', models.CharField(max_length=50)),
                ('gb', models.IntegerField()),
                ('bus', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='tarjetas_video')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppGestion.marca')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppGestion.tipo')),
            ],
        ),
    ]
